# Generated by Django 3.0.8 on 2020-07-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Descripton',
        ),
        migrations.AddField(
            model_name='item',
            name='Description',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
