# Generated by Django 3.0.8 on 2020-07-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200710_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=500, null=True)),
                ('Phone', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.ManyToManyField(related_name='Things', to='dashboard.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='vendor',
            field=models.ManyToManyField(related_name='Items', to='dashboard.Vendor'),
        ),
    ]
