# Generated by Django 3.0.8 on 2020-07-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200710_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Cost',
            field=models.DecimalField(decimal_places=2, default=0.01, max_digits=5),
        ),
    ]
