# Generated by Django 3.0.8 on 2020-07-11 11:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='recently_viewed',
            field=models.ManyToManyField(related_name='recently_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
