# Generated by Django 3.0.8 on 2020-07-11 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_item_recently_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='recently_viewed',
            field=models.ManyToManyField(max_length=10, related_name='recently_viewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
